import { useMemo, useState } from 'react';

const KEY='ourhome_cat_vault_v1';
const DEFAULT={accounts:[
{id:'cash',name:'微信零钱',type:'asset',balance:368.52,emoji:'💚'},
{id:'card',name:'工资卡',type:'asset',balance:5200,emoji:'💳'},
{id:'alipay',name:'支付宝余额',type:'asset',balance:126.8,emoji:'🟦'},
{id:'huabei',name:'花呗待还',type:'debt',balance:275.43,emoji:'🌸'}],
transactions:[{id:'seed-1',date:new Date().toISOString().slice(0,10),type:'expense',amount:18,category:'餐饮',accountId:'cash',tag:'必要',note:'午饭'}],
goals:[{id:'goal-1',name:'旅行基金',target:5000,current:2000,emoji:'✈️'}],budget:1500};
const PHRASES=['今天也在认真生活，辛苦啦。','记下来的每一笔，都是你在把日子握回手里。','少一点糊涂账，多一点安心。','小金库又长大了一点点。'];
const money=v=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const load=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));return x?.accounts?x:DEFAULT}catch{return DEFAULT}};
const emptyAccount=()=>({id:'',name:'',type:'asset',balance:'',emoji:'💳'});

export default function VaultPage({onClose}){
 const [data,setData]=useState(load),[tab,setTab]=useState('home'),[showForm,setShowForm]=useState(false),[showAccounts,setShowAccounts]=useState(false),[accountForm,setAccountForm]=useState(emptyAccount),[phrase,setPhrase]=useState(PHRASES[0]);
 const [form,setForm]=useState({type:'expense',amount:'',category:'餐饮',accountId:data.accounts[0]?.id||'',tag:'必要',note:'',date:new Date().toISOString().slice(0,10)});
 const commit=n=>{setData(n);localStorage.setItem(KEY,JSON.stringify(n))};
 const totals=useMemo(()=>{const month=new Date().toISOString().slice(0,7),rows=data.transactions.filter(x=>x.date.startsWith(month)),assets=data.accounts.filter(x=>x.type==='asset').reduce((s,x)=>s+Number(x.balance),0),debt=data.accounts.filter(x=>x.type==='debt').reduce((s,x)=>s+Number(x.balance),0),income=rows.filter(x=>x.type==='income').reduce((s,x)=>s+Number(x.amount),0),expense=rows.filter(x=>x.type==='expense').reduce((s,x)=>s+Number(x.amount),0),unnecessary=rows.filter(x=>x.type==='expense'&&x.tag==='非必要').reduce((s,x)=>s+Number(x.amount),0);return{net:assets-debt,income,expense,unnecessary}},[data]);
 const submit=e=>{e.preventDefault();const amount=Number(form.amount);if(!amount||!form.accountId)return;const row={...form,amount,id:crypto.randomUUID()},accounts=data.accounts.map(a=>{if(a.id!==form.accountId)return a;let d=form.type==='income'?amount:-amount;if(a.type==='debt')d=form.type==='expense'?amount:-amount;return{...a,balance:Number(a.balance)+d}});commit({...data,accounts,transactions:[row,...data.transactions]});setPhrase(PHRASES[Math.floor(Math.random()*PHRASES.length)]);setForm(x=>({...x,amount:'',note:''}));setShowForm(false)};
 const deleteRow=row=>{const accounts=data.accounts.map(a=>{if(a.id!==row.accountId)return a;let d=row.type==='income'?-Number(row.amount):Number(row.amount);if(a.type==='debt')d=row.type==='expense'?-Number(row.amount):Number(row.amount);return{...a,balance:Number(a.balance)+d}});commit({...data,accounts,transactions:data.transactions.filter(x=>x.id!==row.id)})};
 const editAccount=a=>setAccountForm(a?{...a,balance:String(a.balance)}:emptyAccount());
 const saveAccount=e=>{e.preventDefault();const balance=Number(accountForm.balance);if(!accountForm.name.trim()||Number.isNaN(balance))return;let accounts,id=accountForm.id;if(id)accounts=data.accounts.map(a=>a.id===id?{...a,...accountForm,name:accountForm.name.trim(),balance,emoji:accountForm.emoji||'💳'}:a);else{id=crypto.randomUUID();accounts=[...data.accounts,{...accountForm,id,name:accountForm.name.trim(),balance,emoji:accountForm.emoji||'💳'}]};commit({...data,accounts});setForm(x=>({...x,accountId:x.accountId||id}));setAccountForm(emptyAccount())};
 const deleteAccount=a=>{const linked=data.transactions.some(r=>r.accountId===a.id);if(!confirm(linked?'这个账户已有历史记录。删除后记录仍保留，并显示为“已删除账户”。确定删除吗？':'确定删除这个账户吗？'))return;const accounts=data.accounts.filter(x=>x.id!==a.id);commit({...data,accounts});setForm(x=>({...x,accountId:x.accountId===a.id?(accounts[0]?.id||''):x.accountId}));setAccountForm(emptyAccount())};
 const card={background:'#FFFDF8',border:'1px solid #EFE4CC',borderRadius:18,boxShadow:'0 6px 20px rgba(78,46,16,.06)'},soft={border:'1px solid #EFD8A6',background:'#FFF3D6',color:'#9A621A',borderRadius:12,padding:'9px 13px',fontWeight:650};
 return <div style={{position:'fixed',inset:0,zIndex:9999,background:'#FFF8F0',color:'#2E1F12',fontFamily:'-apple-system,"PingFang SC","Microsoft YaHei",sans-serif',display:'flex',flexDirection:'column'}}>
  <header style={{padding:'14px 16px 10px',background:'#FFFDF8',borderBottom:'1px solid #EFE4CC'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8}}><button onClick={onClose} style={soft}>← 回家</button><div style={{textAlign:'center'}}><div style={{fontSize:19,fontWeight:800,letterSpacing:'.12em'}}>猫の金库</div><div style={{fontSize:10,color:'#B89A6A',letterSpacing:'.25em'}}>OUR LITTLE VAULT</div></div><button onClick={()=>{setShowAccounts(true);editAccount()}} style={{...soft,padding:'8px 10px'}}>账户</button></div></header>
  <main style={{flex:1,overflowY:'auto',padding:'16px 14px 100px'}}>
   {tab==='home'&&<><section style={{...card,padding:20,background:'linear-gradient(145deg,#FFF7DE,#F8DFAB)'}}><div style={{color:'#9A7A50',fontSize:12}}>净资产</div><div style={{fontSize:34,fontWeight:850}}>¥ {money(totals.net)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:18}}><Mini label="本月收入" value={totals.income} plus/><Mini label="本月支出" value={totals.expense}/></div></section><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',margin:'22px 4px 10px'}}><h3 style={{margin:0}}>我的账户</h3><button onClick={()=>{setShowAccounts(true);editAccount()}} style={{border:0,background:'transparent',color:'#9A621A',fontWeight:700}}>管理</button></div><div style={{display:'grid',gap:10}}>{data.accounts.map(a=><button key={a.id} onClick={()=>{setShowAccounts(true);editAccount(a)}} style={{...card,padding:'14px 15px',display:'flex',alignItems:'center',gap:12,textAlign:'left',color:'inherit'}}><span style={{fontSize:22}}>{a.emoji}</span><span style={{flex:1}}><b>{a.name}</b><small style={{display:'block',color:'#B89A6A'}}>{a.type==='debt'?'负债账户':'资产账户'}</small></span><b style={{color:a.type==='debt'?'#C36F5C':'inherit'}}>¥ {money(a.balance)}</b></button>)}</div><h3 style={{margin:'22px 4px 10px'}}>本月预算</h3><section style={{...card,padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><span>已用 ¥ {money(totals.expense)}</span><span>预算 ¥ {money(data.budget)}</span></div><div style={{height:10,borderRadius:99,background:'#F2E7D2',overflow:'hidden',marginTop:10}}><div style={{height:'100%',width:`${Math.min(100,totals.expense/Math.max(1,data.budget)*100)}%`,background:'#DD9A33'}}/></div><div style={{marginTop:10,color:'#9A7A50'}}>非必要支出 ¥ {money(totals.unnecessary)}</div></section><section style={{...card,padding:18,marginTop:18,textAlign:'center'}}><small style={{color:'#B89A6A'}}>老公的话</small><div style={{marginTop:10}}>“{phrase}”</div></section></>}
   {tab==='records'&&<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><h3>收支记录</h3><button onClick={()=>setShowForm(true)} style={soft}>记一笔</button></div><div style={{display:'grid',gap:10}}>{data.transactions.map(r=>{const a=data.accounts.find(x=>x.id===r.accountId);return <div key={r.id} style={{...card,padding:14,display:'flex',gap:10,alignItems:'center'}}><span style={{fontSize:22}}>{r.type==='income'?'🌱':'🧾'}</span><span style={{flex:1}}><b>{r.note||r.category}</b><small style={{display:'block',color:'#B89A6A'}}>{r.date} · {a?.name||'已删除账户'} · {r.tag||''}</small></span><span style={{textAlign:'right'}}><b style={{color:r.type==='income'?'#5D8C62':'#C36F5C'}}>{r.type==='income'?'+':'-'}¥ {money(r.amount)}</b><button onClick={()=>deleteRow(r)} style={{display:'block',border:0,background:'transparent',color:'#C7A77A'}}>删除</button></span></div>})}</div></>}
   {tab==='stats'&&<><h3>本月统计</h3><section style={{...card,padding:18}}><Stat label="收入" value={totals.income}/><Stat label="支出" value={totals.expense}/><Stat label="非必要" value={totals.unnecessary}/></section></>}
   {tab==='goals'&&<><h3>存钱目标</h3>{data.goals.map(g=><section key={g.id} style={{...card,padding:17}}><b>{g.emoji} {g.name}</b><div style={{marginTop:10}}>¥ {money(g.current)} / ¥ {money(g.target)}</div></section>)}</>}
  </main>
  <nav style={{position:'fixed',left:0,right:0,bottom:0,display:'grid',gridTemplateColumns:'repeat(4,1fr)',background:'#FFFDF8',borderTop:'1px solid #EFE4CC',padding:8}}>{[['home','🏠','总览'],['records','🧾','明细'],['stats','📊','统计'],['goals','🎯','目标']].map(([k,i,l])=><button key={k} onClick={()=>setTab(k)} style={{border:0,background:tab===k?'#FFF3D6':'transparent',borderRadius:12,padding:7}}><div>{i}</div><small>{l}</small></button>)}</nav>
  {showForm&&<Modal close={()=>setShowForm(false)}><form onSubmit={submit}><Title text="记一笔" close={()=>setShowForm(false)}/><Field label="收支类型"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} style={input}><option value="expense">支出</option><option value="income">收入</option></select></Field><Field label="金额"><input value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} inputMode="decimal" style={input}/></Field><Field label="日期"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} style={input}/></Field><Field label="分类"><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} style={input}>{['餐饮','交通','购物','住房','娱乐','工资','红包','其他'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="账户"><select value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})} style={input}><option value="">请选择账户</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field><Field label="标签"><select value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})} style={input}><option>必要</option><option>非必要</option></select></Field><Field label="备注"><input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} style={input}/></Field><button style={primary}>保存记录</button></form></Modal>}
  {showAccounts&&<Modal close={()=>setShowAccounts(false)}><Title text="管理账户" close={()=>setShowAccounts(false)}/><div style={{display:'grid',gap:8,marginTop:15}}>{data.accounts.map(a=><button key={a.id} onClick={()=>editAccount(a)} style={{...card,padding:12,display:'flex',gap:10,textAlign:'left',color:'inherit'}}><span>{a.emoji}</span><span style={{flex:1}}><b>{a.name}</b><small style={{display:'block',color:'#B89A6A'}}>{a.type==='debt'?'负债':'资产'} · ¥ {money(a.balance)}</small></span><span>编辑</span></button>)}</div><form onSubmit={saveAccount} style={{borderTop:'1px solid #EFE4CC',marginTop:18}}><h4>{accountForm.id?'修改账户':'添加账户'}</h4><Field label="账户名称"><input value={accountForm.name} onChange={e=>setAccountForm({...accountForm,name:e.target.value})} style={input}/></Field><Field label="图标"><input value={accountForm.emoji} onChange={e=>setAccountForm({...accountForm,emoji:e.target.value})} style={input}/></Field><Field label="当前余额"><input value={accountForm.balance} onChange={e=>setAccountForm({...accountForm,balance:e.target.value})} inputMode="decimal" style={input}/></Field><Field label="账户类型"><select value={accountForm.type} onChange={e=>setAccountForm({...accountForm,type:e.target.value})} style={input}><option value="asset">资产账户</option><option value="debt">负债账户</option></select></Field><div style={{display:'grid',gridTemplateColumns:accountForm.id?'1fr 1fr':'1fr',gap:10}}>{accountForm.id&&<button type="button" onClick={()=>deleteAccount(accountForm)} style={{...soft,color:'#B75D50'}}>删除账户</button>}<button style={{...primary,marginTop:0}}>{accountForm.id?'保存修改':'添加账户'}</button></div>{accountForm.id&&<button type="button" onClick={()=>editAccount()} style={{width:'100%',border:0,background:'transparent',marginTop:12}}>＋ 添加另一个账户</button>}</form></Modal>}
 </div>
}
const input={width:'100%',boxSizing:'border-box',border:'1px solid #E9D8B8',borderRadius:12,padding:11,background:'#FFFDF8',fontSize:14};
const primary={width:'100%',marginTop:20,border:0,borderRadius:14,padding:14,background:'#C8892A',color:'#fff',fontWeight:800};
function Modal({close,children}){return <div onClick={close} style={{position:'fixed',inset:0,zIndex:10000,background:'rgba(36,24,12,.35)',display:'flex',alignItems:'flex-end'}}><div onClick={e=>e.stopPropagation()} style={{width:'100%',maxHeight:'90vh',overflowY:'auto',background:'#FFFDF8',borderRadius:'24px 24px 0 0',padding:'20px 18px 28px'}}>{children}</div></div>}
function Title({text,close}){return <div style={{display:'flex',justifyContent:'space-between'}}><h3 style={{margin:0}}>{text}</h3><button onClick={close} style={{border:0,background:'transparent',fontSize:22}}>×</button></div>}
function Field({label,children}){return <label style={{display:'block',marginTop:14}}><div style={{fontSize:12,color:'#9A7A50',marginBottom:6}}>{label}</div>{children}</label>}
function Mini({label,value,plus}){return <div style={{background:'rgba(255,255,255,.58)',borderRadius:13,padding:12}}><small>{label}</small><div><b>{plus?'+':'-'}¥ {money(value)}</b></div></div>}
function Stat({label,value}){return <div style={{display:'flex',justifyContent:'space-between',padding:12,borderBottom:'1px solid #EFE4CC'}}><span>{label}</span><b>¥ {money(value)}</b></div>}
